### PR TITLE
Ruby on Rails capstone project - Budget app

### PR DESCRIPTION
**Pull request by ZahraArshia**
Hello 😀 
This is my Ruby on Rails capstone project, which is a mobile web application to manage budget. it allows the user to:

- register and log in, so that the data is private to them.
- introduce new transactions associated with a category.
- see the money spent on each category.

Live demo : https://thawing-taiga-04921.herokuapp.com/

Description video : https://www.loom.com/share/6b59cfa6cf814b4b949fe23785d47dd4

Project requirements : https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#project-requirements

Result:
image

Tests:
image

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @ZahraArshia, This is @sja-thedude your code reviewer.

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Good PR description & title
✔️ All linters are passing
✔️ Professional Readme
✔️ Congratulations 🎊  on completing all the project requirements just a step away from approval

## Required 
- [ ] Kindly highlight a piece of the code you find interesting or are proud of making in the video presentation.
_You can just make a new video just showing the above requirement._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ZahraArshia** [comment]
Hello again 😄, I recorded a separated video as required to explain about the code structure: https://www.loom.com/share/191102e0d90b4deb8bcd641941264b17

**Comment by ZahraArshia** [comment]
Hello again :smil

**Review by hiromataba — APPROVED** [review]
# Status: Approved :tada: :tada: :tada: 
Hi @ZahraArshia     :wave: :wave: 

200w  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
